### PR TITLE
Minor changes to the copy code

### PR DESCRIPTION
**Pull request by xyproto**
Also added _test file which is pretty empty right now, but where tests can be added.

### CODE REVIEW

**Comment by xyproto** [comment]
The original copy code was based on a gist. These changes are mainly based on a gist that was based on the original gist: https://gist.github.com/kuznero/41acd2afdbe7cfd8e135c4573041e1da

The file copying will probably have to be tested properly in the `copy_test.go` file, to make sure the desired behavior is achieved.

**Comment by Foxboron** [comment]
The main issues is we set the UID and GID as we also move it between the container and PKGDEST, so that part needs to go somewhere. I'm also unsure if the proposed patch works with the `/etc/pacman.d/gnupg` directory as it contains a socket.

I think `CopyDir` should return `map[string]string` where you have `filename -> directory` so we know what files where moved.

**Comment by xyproto** [comment]
I guess we need a test, to be sure. I like the idea of CopyDir returning a map!

**Comment by Foxboron** [comment]
Merged and added code to omit sockets.

**Pull request merged**
